### PR TITLE
added pr-train logo

### PR DESCRIPTION
**Pull request by deboutlaw**
added a cool logo!

### CODE REVIEW

**Comment by itaditya** [comment]
Hi @deboutlaw thanks for volunteering to work on this. I saw the logo but it has some issues like it doesn't match the colors used in the app. Another thing is that the logo will be used as a favicon in the Title Bar. So it would be better if the logo is a symbol type rather than typography type.

**Comment by deboutlaw** [comment]
ok let me see what I can do =)

**Comment by deboutlaw** [comment]
What about something like this? It is actually the 'MT extra font' with the letters p r t typed!





favicon-16x16
favicon-32x32

**Comment by itaditya** [comment]
Hi @deboutlaw thanks for spending time on this. I got a really great logo so I have picked that one https://github.com/itaditya/pr-train/blob/master/public/logo-180x180.png.

**Comment by deboutlaw** [comment]
@itaditya thanks so much for allowing me to work on this and learn!

**Pull request closed without merging**
